sudo: required

language: generic

services: 
  - docker

before_install:
  - docker build -t alvinsoo/docker-react -f Dockerfile.dev .

script:
  - docker run alvinsoo/docker-react npm run test -- --coverage